CREATE TABLE users (
   id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   email    VARCHAR(128) NOT NULL UNIQUE,
   password VARCHAR(128) NOT NULL,
   username VARCHAR(128) NOT NULL,
   profile  VARCHAR(128) NOT NULL,
   affiliation_id BIGINT NOT NULL,
   position_id BIGINT NOT NULL,
   FOREIGN KEY (affiliation_id) REFERENCES affiliations(id) ON DELETE CASCADE,
   FOREIGN KEY (position_id) REFERENCES positions(id) ON DELETE CASCADE
);