CREATE TABLE comments (
   id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   comment      VARCHAR(128) NOT NULL,
   user_id      BIGINT NOT NULL,
   prototype_id BIGINT NOT NULL,
   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
   FOREIGN KEY (prototype_id) REFERENCES prototypes(id) ON DELETE CASCADE
);