spring.application.name=prototype-d
spring.datasource.url=jdbc:postgresql://localhost:5432/protospace_d
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver