spring.application.name=prototype-d
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/protospace_d}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# DDLの自動実行を無効化 (Flywayを使うため)
spring.jpa.hibernate.ddl-auto=validate
# SQLログを出力しない (パフォーマンス向上のため)
spring.jpa.show-sql=false
server.port=${PORT:8080}
#Render用のHTTPSプロキシ対策
server.forward-headers-strategy=framework