spring.application.name=prototype-d
spring.datasource.url=jdbc:postgresql://localhost:5432/protospace_d
spring.datasource.username=kiri
spring.datasource.password=taisei0323
spring.datasource.driver-class-name=org.postgresql.Driver